name: Build and Deploy Multi-User

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    env:
      SBNOTE_APP_PATH: ~/apps/sbnote
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      run: |
        docker buildx build \
          --platform linux/amd64 \
          --tag yamnor/sbnote:latest \
          --tag yamnor/sbnote:${{ github.sha }} \
          --push .
    
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Deploy to server
      run: |
        # Deploy using manage-users.sh
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
        set -euo pipefail
        
        # Apply Docker group membership for this session
        newgrp docker
        
        # Deploy all users from configuration
        ${{ env.SBNOTE_APP_PATH }}/manage-users.sh deploy
        
        echo "Deployment completed successfully!"
        EOF